/**
 * Add prefixes to our compiled CSS files
 */
module.exports = function( grunt ) {
	grunt.config( 'postcss', {
		options: {
			map: '<%= development %>',
			processors: [
				require('autoprefixer')({browsers: 'last 2 versions'}), // add vendor prefixes
				require('cssnano')({
					preset: 'default',
					reduceIdents: false,
					zindex: false,
					mergeIdents: false,
					discardUnused: false,
				}), // minify the result
				require('postcss-banner')({
					banner:
						grunt.template.process(
							'<%= pkg.plugin_name %>' + '\n' +
							'' + '\n' +
							'Autogenerated by Grunt on: <%= grunt.template.today("yyyy-mm-dd") %>' + '\n' +
							'@version <%= pkg.version %>' + '\n' +
							'@author <%= pkg.author %>' + '\n' +
							'@license <%= pkg.license %>'
						),
					important: true,
				}),
			],
		},
		admin: {
			src: '<%= paths.sass.admin.dest %>/**/*<%= paths.sass.ext %>',
		},
		front: {
			src: '<%= paths.sass.front.dest %>/**/*<%= paths.sass.ext %>',
		}
	} );

	grunt.registerTask( 'postcss:all', [ 'postcss:admin', 'postcss:front' ] );
};
